# Generated by Django 3.2.5 on 2021-08-11 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'Perfiles'},
        ),
    ]
