# Generated by Django 3.2.5 on 2021-08-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_alter_perfil_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='provincia',
            field=models.CharField(default='provincia', max_length=150),
            preserve_default=False,
        ),
    ]
